/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.livrosurpresa.view;

import br.com.livrosurpresa.dao.ClienteDao;
import br.com.livrosurpresa.dao.LivroDao;
import br.com.livrosurpresa.dao.RecebeDao;
import br.com.livrosurpresa.models.Cliente;
import br.com.livrosurpresa.models.Livro;
import br.com.livrosurpresa.models.Recebe;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.jdesktop.observablecollections.ObservableCollections;

/**
 *
 * @author bela
 */
public class tela_exibicao extends javax.swing.JFrame {

    /**
     * Creates new form tela_exibicao
     */
    
    public tela_exibicao(){
        initComponents();
    }
   
    
    private ClienteDao dc;
    private LivroDao dl;
    private RecebeDao dr;
    
     private Cliente cliente;

    public static final String PROP_CLIENTE = "cliente";

    public Cliente getCliente() {
        return cliente;
    }

    public void setCliente(Cliente cliente) {
        Cliente oldCliente = this.cliente;
        this.cliente = cliente;
        firePropertyChange(PROP_CLIENTE, oldCliente, cliente);
    }

    private Livro livro;

    public static final String PROP_LIVRO = "livro";

    public Livro getLivro() {
        return livro;
    }

    public void setLivro(Livro livro) {
        Livro oldLivro = this.livro;
        this.livro = livro;
        firePropertyChange(PROP_LIVRO, oldLivro, livro);
    }
    
    private Recebe recebido;

    public static final String PROP_RECEBIDO = "recebido";

    public Recebe getRecebido() {
        return recebido;
    }

    public void setRecebido(Recebe recebido) {
        Recebe oldRecebido = this.recebido;
        this.recebido = recebido;
        firePropertyChange(PROP_RECEBIDO, oldRecebido, recebido);
    }

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        list_cliente = ObservableCollections.observableList(new ArrayList<Cliente>());
        list_livro = ObservableCollections.observableList(new ArrayList<Livro>());
        list_recebidos = ObservableCollections.observableList(new ArrayList<Recebe>());
        jLabel20 = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        tfLivroAutor = new javax.swing.JTextField();
        btSalvar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbLivro1 = new javax.swing.JTable();
        btExcluir = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        btSalvar1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbLivro = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbCliente = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfClienteCidade = new javax.swing.JTextField();
        tfLivroPags = new javax.swing.JTextField();
        tfClienteNome = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tfClienteNumero = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tfClienteRua = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tfClienteEmail = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jComboLivroGenero = new javax.swing.JComboBox<>();
        tfLivroNome = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfClienteCpf = new javax.swing.JFormattedTextField();
        tfClienteTelefone = new javax.swing.JFormattedTextField();
        tfLivroAno = new javax.swing.JTextField();
        tfClienteUf = new javax.swing.JFormattedTextField();
        tfLivroEditora = new javax.swing.JTextField();
        tfClienteCep = new javax.swing.JFormattedTextField();
        jLabel22 = new javax.swing.JLabel();
        tfClienteCpfExcluir = new javax.swing.JFormattedTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        tfLivroIdExcluir = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel20.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        jLabel20.setText("Editora");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 457, Short.MAX_VALUE)
        );

        tfLivroAutor.setBackground(new java.awt.Color(210, 190, 179));
        tfLivroAutor.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        tfLivroAutor.setForeground(new java.awt.Color(36, 36, 36));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${livro.autor}"), tfLivroAutor, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        btSalvar.setBackground(new java.awt.Color(145, 119, 102));
        btSalvar.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        btSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btSalvar.setText("Inserir");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        tbLivro1.setBackground(new java.awt.Color(210, 190, 179));
        tbLivro1.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        tbLivro1.setForeground(new java.awt.Color(36, 36, 36));
        tbLivro1.setEnabled(false);
        tbLivro1.setGridColor(new java.awt.Color(161, 95, 64));

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, list_recebidos, tbLivro1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cpf_cliente}"));
        columnBinding.setColumnName("Cpf_cliente");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${id_livro}"));
        columnBinding.setColumnName("Id_livro");
        columnBinding.setColumnClass(Integer.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane3.setViewportView(tbLivro1);

        btExcluir.setBackground(new java.awt.Color(145, 119, 102));
        btExcluir.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        btExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btLimpar.setBackground(new java.awt.Color(145, 119, 102));
        btLimpar.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        btLimpar.setForeground(new java.awt.Color(255, 255, 255));
        btLimpar.setText("Limpar");
        btLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btLimparMouseClicked(evt);
            }
        });
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Georgia", 1, 15)); // NOI18N
        jLabel21.setText("RESULTADOS DO SORTEIO:");

        jComboBox1.setBackground(new java.awt.Color(210, 190, 179));
        jComboBox1.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(51, 51, 51));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONAR", "CLIENTE", "LIVRO" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        btSalvar1.setBackground(new java.awt.Color(161, 101, 64));
        btSalvar1.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        btSalvar1.setForeground(new java.awt.Color(255, 255, 255));
        btSalvar1.setText("Realizar Sorteio");
        btSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvar1ActionPerformed(evt);
            }
        });

        tbLivro.setBackground(new java.awt.Color(210, 190, 179));
        tbLivro.setFont(new java.awt.Font("Noto Serif CJK KR", 0, 15)); // NOI18N
        tbLivro.setForeground(new java.awt.Color(36, 36, 36));
        tbLivro.setEnabled(false);
        tbLivro.setGridColor(new java.awt.Color(161, 95, 64));

        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, list_livro, tbLivro);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${id}"));
        columnBinding.setColumnName("Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nome}"));
        columnBinding.setColumnName("Nome");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${autor}"));
        columnBinding.setColumnName("Autor");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${ano}"));
        columnBinding.setColumnName("Ano");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${editora}"));
        columnBinding.setColumnName("Editora");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${genero}"));
        columnBinding.setColumnName("Genero");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${num_paginas}"));
        columnBinding.setColumnName("Num_paginas");
        columnBinding.setColumnClass(Integer.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(tbLivro);

        jLabel15.setFont(new java.awt.Font("Georgia", 1, 15)); // NOI18N
        jLabel15.setText("CLIENTE");

        jLabel19.setFont(new java.awt.Font("Georgia", 0, 20)); // NOI18N
        jLabel19.setText("Exclusão:");

        jLabel9.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        jLabel9.setText("Email");

        tbCliente.setBackground(new java.awt.Color(210, 190, 179));
        tbCliente.setFont(new java.awt.Font("Noto Serif CJK KR", 0, 15)); // NOI18N
        tbCliente.setForeground(new java.awt.Color(36, 36, 36));
        tbCliente.setEnabled(false);
        tbCliente.setFocusCycleRoot(true);
        tbCliente.setGridColor(new java.awt.Color(161, 95, 64));
        tbCliente.setInheritsPopupMenu(true);

        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, list_cliente, tbCliente);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nome}"));
        columnBinding.setColumnName("Nome");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cpf}"));
        columnBinding.setColumnName("Cpf");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${telefone}"));
        columnBinding.setColumnName("Telefone");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${email}"));
        columnBinding.setColumnName("Email");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cidade}"));
        columnBinding.setColumnName("Cidade");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${rua}"));
        columnBinding.setColumnName("Rua");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${numero}"));
        columnBinding.setColumnName("Numero");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cep}"));
        columnBinding.setColumnName("Cep");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${uf}"));
        columnBinding.setColumnName("Uf");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane2.setViewportView(tbCliente);

        jLabel10.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        jLabel10.setText("Telefone");

        jLabel11.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        jLabel11.setText("Ano");

        tfClienteCidade.setBackground(new java.awt.Color(210, 190, 179));
        tfClienteCidade.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        tfClienteCidade.setForeground(new java.awt.Color(36, 36, 36));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${cliente.cidade}"), tfClienteCidade, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        tfClienteCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfClienteCidadeActionPerformed(evt);
            }
        });

        tfLivroPags.setBackground(new java.awt.Color(210, 190, 179));
        tfLivroPags.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        tfLivroPags.setForeground(new java.awt.Color(36, 36, 36));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${livro.num_paginas}"), tfLivroPags, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        tfClienteNome.setBackground(new java.awt.Color(210, 190, 179));
        tfClienteNome.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        tfClienteNome.setForeground(new java.awt.Color(36, 36, 36));
        tfClienteNome.setCaretColor(new java.awt.Color(161, 111, 111));
        tfClienteNome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${cliente.nome}"), tfClienteNome, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jLabel12.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        jLabel12.setText("Genero");

        tfClienteNumero.setBackground(new java.awt.Color(210, 190, 179));
        tfClienteNumero.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        tfClienteNumero.setForeground(new java.awt.Color(36, 36, 36));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${cliente.numero}"), tfClienteNumero, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jLabel13.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        jLabel13.setText("N. de Páginas");

        tfClienteRua.setBackground(new java.awt.Color(210, 190, 179));
        tfClienteRua.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        tfClienteRua.setForeground(new java.awt.Color(36, 36, 36));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${cliente.rua}"), tfClienteRua, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jLabel14.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        jLabel14.setText("Autor");

        tfClienteEmail.setBackground(new java.awt.Color(210, 190, 179));
        tfClienteEmail.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${cliente.email}"), tfClienteEmail, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        tfClienteEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfClienteEmailActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Georgia", 1, 15)); // NOI18N
        jLabel17.setText("LIVRO");

        jComboLivroGenero.setBackground(new java.awt.Color(210, 190, 179));
        jComboLivroGenero.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        jComboLivroGenero.setForeground(new java.awt.Color(36, 36, 36));
        jComboLivroGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolher", "Romance", "Terror", "Ficcao" }));

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${livro.genero}");
        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, jComboLivroGenero);
        bindingGroup.addBinding(jComboBoxBinding);

        jComboLivroGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboLivroGeneroActionPerformed(evt);
            }
        });

        tfLivroNome.setBackground(new java.awt.Color(210, 190, 179));
        tfLivroNome.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        tfLivroNome.setForeground(new java.awt.Color(36, 36, 36));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${livro.nome}"), tfLivroNome, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jLabel18.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        jLabel18.setText("Nome");

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 20)); // NOI18N
        jLabel1.setText("Cliente:");

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        jLabel2.setText("Nome");

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        jLabel3.setText("CPF");

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        jLabel4.setText("Número");

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        jLabel5.setText("CEP");

        jLabel6.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        jLabel6.setText("UF");

        jLabel7.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        jLabel7.setText("Cidade");

        jLabel8.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        jLabel8.setText("Rua");

        tfClienteCpf.setBackground(new java.awt.Color(210, 190, 179));
        tfClienteCpf.setForeground(new java.awt.Color(36, 36, 36));
        try {
            tfClienteCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfClienteCpf.setText("");
        tfClienteCpf.setCaretColor(new java.awt.Color(161, 95, 64));
        tfClienteCpf.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        tfClienteCpf.setSelectionColor(new java.awt.Color(161, 95, 64));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${cliente.cpf}"), tfClienteCpf, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        tfClienteCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfClienteCpfActionPerformed(evt);
            }
        });

        tfClienteTelefone.setBackground(new java.awt.Color(210, 190, 179));
        tfClienteTelefone.setForeground(new java.awt.Color(36, 36, 36));
        try {
            tfClienteTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfClienteTelefone.setText("");
        tfClienteTelefone.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${cliente.telefone}"), tfClienteTelefone, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        tfClienteTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfClienteTelefoneActionPerformed(evt);
            }
        });

        tfLivroAno.setBackground(new java.awt.Color(210, 190, 179));
        tfLivroAno.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        tfLivroAno.setForeground(new java.awt.Color(36, 36, 36));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${livro.ano}"), tfLivroAno, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        tfLivroAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLivroAnoActionPerformed(evt);
            }
        });

        tfClienteUf.setBackground(new java.awt.Color(210, 190, 179));
        try {
            tfClienteUf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("UU")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfClienteUf.setText("");
        tfClienteUf.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${cliente.uf}"), tfClienteUf, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        tfClienteUf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfClienteUfActionPerformed(evt);
            }
        });

        tfLivroEditora.setBackground(new java.awt.Color(210, 190, 179));
        tfLivroEditora.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        tfLivroEditora.setForeground(new java.awt.Color(36, 36, 36));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${livro.editora}"), tfLivroEditora, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        tfLivroEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLivroEditoraActionPerformed(evt);
            }
        });

        tfClienteCep.setBackground(new java.awt.Color(210, 190, 179));
        tfClienteCep.setForeground(new java.awt.Color(36, 36, 36));
        try {
            tfClienteCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfClienteCep.setText("");
        tfClienteCep.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${cliente.cep}"), tfClienteCep, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        jLabel22.setFont(new java.awt.Font("Georgia", 0, 20)); // NOI18N
        jLabel22.setText("Ficha do Livro:");

        tfClienteCpfExcluir.setBackground(new java.awt.Color(210, 190, 179));
        tfClienteCpfExcluir.setForeground(new java.awt.Color(36, 36, 36));
        try {
            tfClienteCpfExcluir.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfClienteCpfExcluir.setText("");
        tfClienteCpfExcluir.setCaretColor(new java.awt.Color(161, 95, 64));
        tfClienteCpfExcluir.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        tfClienteCpfExcluir.setSelectionColor(new java.awt.Color(161, 95, 64));
        tfClienteCpfExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfClienteCpfExcluirActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        jLabel23.setText("CPF");

        jLabel24.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        jLabel24.setText("Id");

        tfLivroIdExcluir.setBackground(new java.awt.Color(210, 190, 179));
        tfLivroIdExcluir.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        tfLivroIdExcluir.setForeground(new java.awt.Color(36, 36, 36));
        tfLivroIdExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLivroIdExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfClienteCidade)
                                    .addComponent(tfClienteNome)
                                    .addComponent(tfClienteNumero)
                                    .addComponent(tfClienteRua)
                                    .addComponent(tfClienteEmail)
                                    .addComponent(tfClienteCpf)
                                    .addComponent(tfClienteTelefone)
                                    .addComponent(tfClienteUf)
                                    .addComponent(tfClienteCep, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tfClienteCpfExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                            .addComponent(tfLivroIdExcluir)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel18)
                                                    .addComponent(jLabel11)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel14)
                                                    .addComponent(jLabel13)
                                                    .addComponent(jLabel20)
                                                    .addComponent(jLabel12))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfLivroNome, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jComboLivroGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(tfLivroAutor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(tfLivroPags, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGap(2, 2, 2))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(tfLivroAno, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                                    .addComponent(tfLivroEditora)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btSalvar1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(274, 274, 274))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(196, 196, 196))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(265, 265, 265))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel22))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(tfClienteCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfLivroNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(tfClienteNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)
                                    .addComponent(tfLivroAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel20)
                                        .addComponent(tfLivroEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tfClienteCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(tfLivroAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfClienteNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(tfLivroPags, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfClienteRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(jComboLivroGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfClienteCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tfClienteUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel19))
                                    .addComponent(jLabel6)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel15)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfClienteEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel23)
                                .addComponent(tfClienteCpfExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(tfClienteTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel24)
                                .addComponent(tfLivroIdExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btLimpar)
                            .addComponent(btExcluir)
                            .addComponent(btSalvar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btSalvar1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>                        

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {                                         
        
        if (jComboBox1.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "Selecione o tipo de intem que você deseja inserir!", "Erro!", JOptionPane.WARNING_MESSAGE);
        }
        if (jComboBox1.getSelectedIndex() == 1){
            if(tfClienteCpfExcluir.getText().equals("")){
                 JOptionPane.showMessageDialog(null, "Digite um CPF válido para inserir!", "Erro!", JOptionPane.WARNING_MESSAGE);
            }else{
                String cpf = tfClienteCpfExcluir.getText();
                
                Cliente c = new Cliente();
                
                c.setCpf(tfClienteCpf.getText());;
                c.setNome(tfClienteNome.getText());
                c.setCep(tfClienteCep.getText());
                c.setNumero(tfClienteNumero.getText());
                c.setRua(tfClienteRua.getText());
                c.setCidade(tfClienteCidade.getText());
                c.setUf(tfClienteUf.getText());
                c.setEmail(tfClienteEmail.getText());
                c.setTelefone(tfClienteTelefone.getText());   
                
                dc.salvar(c);
            }
        if (jComboBox1.getSelectedIndex() == 2){
             if(tfLivroIdExcluir.getText().equals("")){
                 JOptionPane.showMessageDialog(null, "Insira um ID válido para excluir.", "Erro!", JOptionPane.WARNING_MESSAGE);
            }else{
                 int id = Integer.parseInt(tfLivroIdExcluir.getText());
                
                 Livro l = new Livro();
                 
                l.setNome(tfLivroNome.getText());
                l.setAno(Integer.parseInt(tfLivroAno.getText()));
                l.setEditora(tfLivroEditora.getText());
                l.setAutor(tfLivroAutor.getText());
                l.setNum_paginas(Integer.parseInt(tfLivroPags.getText()));
                l.setGenero((String) jComboLivroGenero.getSelectedItem());
                dl.salvar(l);
            }
        
        }
        
        listar();

    }                                        
    
    }public void listar(){
        list_livro.clear();
        list_cliente.clear();
        list_recebidos.clear();
        
        list_livro.addAll(dl.getAll());
        list_cliente.addAll(dc.getAll());
        list_recebidos.addAll(dr.getAll());
    }
    
    public void limpar(){
        if (jComboBox1.getSelectedIndex() == 0){
            
            JOptionPane.showMessageDialog(null, "Selecione uma opção válida para limpar!", "Erro!", JOptionPane.WARNING_MESSAGE);
        
        }
        
        else if (jComboBox1.getSelectedIndex() == 1){
            
            tfClienteCpf.setText("");
            tfClienteNome.setText("");
            tfClienteCep.setText("");
            tfClienteNumero.setText("");
            tfClienteRua.setText("");
            tfClienteCidade.setText("");
            tfClienteUf.setText("");
            tfClienteEmail.setText("");
            tfClienteTelefone.setText("");   
                        
        }
        
        else{
            
            tfLivroNome.setText("");
            tfLivroNome.setText("");
            tfLivroEditora.setText("");
            tfLivroAutor.setText("");
            tfLivroPags.setText("");
            jComboLivroGenero.setSelectedIndex(0);

        }
    }
    private void btLimparMouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        
    }                                        

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void btSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        int qtd_livros = list_livro.size();
        int sorteado = -1;
        Recebe recebeu = new Recebe();
        Random r = new Random();
        for(int i = 0; i<list_cliente.size(); i++){
            recebeu.setCpf_cliente(list_cliente.get(i).getCpf());
            sorteado = r.nextInt(qtd_livros);
            for(int j=0; j<qtd_livros; j++){
                if(j == sorteado){
                    recebeu.setId_livro(list_livro.get(j).getId());
                    j = qtd_livros;
                }
            }
            dr.salvar(recebeu);
        }
        listar();
    }                                         

    private void tfClienteCidadeActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    private void tfClienteEmailActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void jComboLivroGeneroActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 

    private void tfClienteCpfActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void tfClienteTelefoneActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 

    private void tfLivroAnoActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void tfClienteUfActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void tfLivroEditoraActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {                                          
        
        if (jComboBox1.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "Selecione o tipo de dados que você deseja excluir.", "Erro!", JOptionPane.WARNING_MESSAGE);
        }
        if (jComboBox1.getSelectedIndex() == 1){
            if(tfClienteCpfExcluir.getText().equals("")){
                 JOptionPane.showMessageDialog(null, "Insira um CPF válido para excluir.", "Erro!", JOptionPane.WARNING_MESSAGE);
            }else{
                String cpf = tfClienteCpfExcluir.getText();
                
                for(int cont=0; cont<list_cliente.size(); cont++){
                    if(list_cliente.get(cont).getCpf().equals(cpf)){
                        dc.remover(list_cliente.get(cont));
                        list_cliente.remove(list_cliente.get(cont));
                    }
                }
                
            }
        if (jComboBox1.getSelectedIndex() == 2){
             if(tfLivroIdExcluir.getText().equals("")){
                 JOptionPane.showMessageDialog(null, "Insira um ID válido para excluir.", "Erro!", JOptionPane.WARNING_MESSAGE);
            }else{
                 int id = Integer.parseInt(tfLivroIdExcluir.getText());
                
                for(int cont=0; cont<list_livro.size(); cont++){
                    if(list_livro.get(cont).getId() == id){ 
                        dl.remover(list_livro.get(cont));
                        list_livro.remove(list_livro.get(cont));
                    }
                }
            }
        
        }
        tfClienteCpfExcluir.setText("");
        tfLivroIdExcluir.setText("");
        listar();
    }                                         
    }
    private void tfClienteCpfExcluirActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
    }                                                   

    private void tfLivroIdExcluirActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_exibicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_exibicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_exibicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_exibicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_exibicao().setVisible(true);
                this.setSize(500,200);
                this.setVisible(true);
                this.setResizable(false);
                this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            }
        });
*/
    }


    // Variables declaration - do not modify                     
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btSalvar1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboLivroGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private java.util.List<Cliente> list_cliente;
    private java.util.List<Livro> list_livro;
    private java.util.List<Recebe> list_recebidos;
    private java.awt.Panel panel1;
    private javax.swing.JTable tbCliente;
    private javax.swing.JTable tbLivro;
    private javax.swing.JTable tbLivro1;
    private javax.swing.JFormattedTextField tfClienteCep;
    private javax.swing.JTextField tfClienteCidade;
    private javax.swing.JFormattedTextField tfClienteCpf;
    private javax.swing.JFormattedTextField tfClienteCpfExcluir;
    private javax.swing.JTextField tfClienteEmail;
    private javax.swing.JTextField tfClienteNome;
    private javax.swing.JTextField tfClienteNumero;
    private javax.swing.JTextField tfClienteRua;
    private javax.swing.JFormattedTextField tfClienteTelefone;
    private javax.swing.JFormattedTextField tfClienteUf;
    private javax.swing.JTextField tfLivroAno;
    private javax.swing.JTextField tfLivroAutor;
    private javax.swing.JTextField tfLivroEditora;
    private javax.swing.JTextField tfLivroIdExcluir;
    private javax.swing.JTextField tfLivroNome;
    private javax.swing.JTextField tfLivroPags;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration                   
}
